[package]
name = "ufe"
version = "0.0.0"
edition = "2021"
description = "User facing error library"
license = "MPL-2.0"
authors = ["Marcel Müller <neikos@neikos.email>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
